name: Connect 4

on:
  issues:
    types: [opened]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Play Game
        uses: jonathangin/connect4-action@v1.2.2
        with:
          issue-number: ${{ github.event.issue.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
